language: node_js
node_js:
  - "node"
  - "9"

before_script:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - npm test

notifications:
  email:
    on_success: never
    on_failuer: always
